[tool.poetry]
name = "helpbotproject"
version = "0.1.0"
description = ""
authors = ["kseniavoitko"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.5.3"
prompt-toolkit = "^3.0.39"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
